### ISSUE TITLE
build failed

### ISSUE THREAD

**Issue by timiil** [teobugslayer/AvaloniaCoreRTDemo#9]
hello, i had git clone the code in windows, 

```
dotnet publish -r win-x64 -c release
```

error info here:

```
EXEC : error : Value cannot be null. (Parameter 'key') [D:\code\avacorert\src\AvaloniaCoreRTDemo.csproj]
  System.ArgumentNullException: Value cannot be null. (Parameter 'key')
     at System.Collections.Generic.Dictionary`2.FindValue(TKey key)
     at System.Collections.Generic.Dictionary`2.TryGetValue(TKey key, TValue& value)
     at ILCompiler.AnalysisBasedMetadataManager.Policy.GeneratesMetadata(EcmaModule module, ExportedTypeHandle exportedTypeHandle)
     at ILCompiler.Metadata.Transform`1.HandleTypeForwarders(EcmaModule module)
     at ILCompiler.Metadata.Transform`1.InitializeScopeDefinition(ModuleDesc module, ScopeDefinition scopeDefinition)
     at ILCompiler.Metadata.EntityMap`2.GetOrCreate[TConcreteEntity,TConcreteRecord](TConcreteEntity entity, Action`2 initializer)
     at ILCompiler.Metadata.Transform`1.HandleNamespaceDefinition(ModuleDesc parentScope, String namespaceString)
     at ILCompiler.Metadata.Transform`1.InitializeTypeDef(MetadataType entity, TypeDefinition record)
     at ILCompiler.Metadata.EntityMap`2.Create[TConcreteEntity,TConcreteRecord](TConcreteEntity entity, Action`2 initializer)
     at ILCompiler.Metadata.Transform`1.HandleType(TypeDesc type)
     at ILCompiler.Metadata.MetadataTransform.Run[TPolicy](TPolicy policy, IEnumerable`1 modules)
     at ILCompiler.GeneratingMetadataManager.ComputeMetadata[TPolicy](TPolicy policy, NodeFactory factory, Byte[]& metadataBlob, List`1& typeMappings, List`1& methodMappings, List`1& fieldMappings, List`1& stackTraceMapping)
     at ILCompiler.AnalysisBasedMetadataManager.ComputeMetadata(NodeFactory factory, Byte[]& metadataBlob, List`1& typeMappings, List`1& methodMappings, List`1& fieldMappings, List`1& stackTraceMapping)
     at ILCompiler.DependencyAnalysis.MetadataNode.GetData(NodeFactory factory, Boolean relocsOnly)
     at ILCompiler.DependencyAnalysis.ObjectWriter.EmitObject(String objectFilePath, IEnumerable`1 nodes, NodeFactory factory, ObjectWritingOptions options, IObjectDumper dumper)
     at ILCompiler.RyuJitCompilation.CompileInternal(String outputFile, ObjectDumper dumper)
     at ILCompiler.Compilation.ILCompiler.ICompilation.Compile(String outputFile, ObjectDumper dumper)
     at ILCompiler.Program.Run(String[] args)
     at ILCompiler.Program.Main(String[] args)
C:\Users\timiil\.nuget\packages\microsoft.dotnet.ilcompiler\6.0.0-preview.4.21206.3\build\Microsoft.NETCore.Native.targets(259,5): error MSB3073: 命令“"C:\Users\timiil\.nuget\packages\runtime.win-x64.microsoft.dotnet.ilcompiler\6.0.0-preview.4.21206.3\tools\ilc" @"obj\Release\net5.0\win-x64\native\AvaloniaCoreRTDemo.ilc.rsp"”已退出，代码为 1。 [D:\code\avacorert\src\AvaloniaCoreRTDemo.csproj]

```

**Comment by teobugslayer** [comment]
I've just tried the command line you provided and the code built and run successfully.

I can assume there was a bad build of the NativeAOT compiler - it happens from time to time. Please try again with the current builds of the .NET 6 SDK.
